-- Executed only by `supabase test db` against the local database.
begin;
select plan(32);
select has_table('profiles');
select has_table('sites');
select has_table('access_requests');
select ok((select relrowsecurity from pg_class where oid='public.profiles'::regclass), 'profiles RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.organizations'::regclass), 'organizations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.organization_memberships'::regclass), 'org memberships RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.sites'::regclass), 'sites RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.site_memberships'::regclass), 'site memberships RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.organization_site_grants'::regclass), 'grants RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.invitations'::regclass), 'invitations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.access_requests'::regclass), 'requests RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.audit_events'::regclass), 'audit RLS enabled');
select has_function('private','current_profile_active', ARRAY['uuid']);
select has_function('private','is_admin_aal2', ARRAY['uuid']);
select has_function('private','can_access_site', ARRAY['uuid','uuid']);
select has_function('private','can_view_org', ARRAY['uuid','uuid']);
select ok((select count(*) from pg_policies where schemaname='public') >= 20, 'explicit policies exist');
select ok((select count(*) from pg_policies where policyname like '%admin%') >= 8, 'admin policies exist');
select ok((select count(*) from pg_policies where tablename='access_requests') >= 4, 'access request policies complete');
select ok((select count(*) from pg_policies where tablename='audit_events') >= 4, 'audit immutable policies');
select ok((select count(*) from pg_policies where tablename='invitations') >= 1, 'invitation policy exists');
select ok((select count(*) from pg_policies where tablename='sites') >= 2, 'site isolation policies');
select ok((select count(*) from pg_policies where tablename='organizations') >= 2, 'organization policies');
select ok((select count(*) from pg_policies where tablename='organization_memberships') >= 2, 'membership policies');
select ok((select count(*) from pg_policies where tablename='site_memberships') >= 2, 'site membership policies');
select ok((select count(*) from pg_policies where tablename='organization_site_grants') >= 2, 'grant policies');
select ok(not has_table_privilege('authenticated','public.invitations','select'), 'invitation select revoked');
select ok(not has_table_privilege('authenticated','public.audit_events','insert'), 'audit insert revoked');
select ok((select prosecdef from pg_proc where proname='can_access_site' and pronamespace='private'::regnamespace), 'helper security definer');
select ok((select prosecdef from pg_proc where proname='can_view_org' and pronamespace='private'::regnamespace), 'org helper security definer');
select ok((select proconfig is not null from pg_proc where proname='can_access_site' and pronamespace='private'::regnamespace), 'helper search path locked');
select ok((select count(*) from pg_policies where schemaname='public' and 'authenticated' = any(roles)) > 0, 'authenticated policies');
select * from finish();
rollback;
