create extension if not exists pgtap with schema extensions;
set search_path = extensions, public, pg_catalog;
begin;
select plan(18);
select has_function('private','current_profile_active_self', ARRAY[]::text[]);
select has_function('private','is_admin_aal2_self', ARRAY[]::text[]);
select has_function('private','can_access_site_self', ARRAY['uuid']);
select has_function('private','can_view_org_self', ARRAY['uuid']);
select has_function('private','can_view_partner_org_self', ARRAY['uuid']);
select ok(not has_function_privilege('authenticated','private.current_profile_active(uuid)','execute'),'legacy helper execute revoked');
select ok(not has_function_privilege('authenticated','private.is_admin_aal2(uuid)','execute'),'legacy admin helper execute revoked');
select ok(not has_function_privilege('authenticated','private.can_access_site(uuid,uuid)','execute'),'legacy site helper execute revoked');
select ok(not has_function_privilege('authenticated','private.can_view_org(uuid,uuid)','execute'),'legacy org helper execute revoked');
select ok(has_function_privilege('authenticated','private.current_profile_active_self()','execute'),'safe active helper execute');
select ok(has_function_privilege('authenticated','private.is_admin_aal2_self()','execute'),'safe admin helper execute');
select ok(has_function_privilege('authenticated','private.can_access_site_self(uuid)','execute'),'safe site helper execute');
select ok(has_function_privilege('authenticated','private.can_view_org_self(uuid)','execute'),'safe org helper execute');
select ok(has_function_privilege('authenticated','private.can_view_partner_org_self(uuid)','execute'),'safe partner helper execute');
select ok(has_table_privilege('authenticated','public.audit_events','select'),'audit select privilege');
select ok(has_table_privilege('authenticated','public.audit_events','insert'),'audit insert privilege');
select ok(not has_table_privilege('authenticated','public.audit_events','update'),'audit update revoked');
select ok(not has_table_privilege('authenticated','public.audit_events','delete'),'audit delete revoked');
select * from finish();
rollback;
