-- Executed only by `supabase test db` against the local database.
create extension if not exists pgtap with schema extensions;
set search_path = extensions, public, pg_catalog;
begin;
select plan(64);
select has_table('profiles');
select has_table('sites');
select has_table('access_requests');
select ok((select relrowsecurity from pg_class where oid='public.profiles'::regclass), 'profiles RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.organizations'::regclass), 'organizations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.organization_memberships'::regclass), 'org memberships RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.sites'::regclass), 'sites RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.site_memberships'::regclass), 'site memberships RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.organization_site_grants'::regclass), 'grants RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.invitations'::regclass), 'invitations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.access_requests'::regclass), 'requests RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.audit_events'::regclass), 'audit RLS enabled');
select has_function('private','current_profile_active', ARRAY['uuid']);
select has_function('private','is_admin_aal2', ARRAY['uuid']);
select has_function('private','can_access_site', ARRAY['uuid','uuid']);
select has_function('private','can_view_org', ARRAY['uuid','uuid']);
select ok((select count(*) from pg_policies where schemaname='public') >= 20, 'explicit policies exist');
select ok((select count(*) from pg_policies where policyname like '%admin%') >= 8, 'admin policies exist');
select ok((select count(*) from pg_policies where tablename='access_requests') >= 4, 'access request policies complete');
select ok((select count(*) from pg_policies where tablename='audit_events') >= 4, 'audit immutable policies');
select ok((select count(*) from pg_policies where tablename='invitations') >= 1, 'invitation policy exists');
select ok((select count(*) from pg_policies where tablename='sites') >= 2, 'site isolation policies');
select ok((select count(*) from pg_policies where tablename='organizations') >= 2, 'organization policies');
select ok((select count(*) from pg_policies where tablename='organization_memberships') >= 2, 'membership policies');
select ok((select count(*) from pg_policies where tablename='site_memberships') >= 2, 'site membership policies');
select ok((select count(*) from pg_policies where tablename='organization_site_grants') >= 2, 'grant policies');
select ok(has_table_privilege('authenticated','public.invitations','select'), 'invitation RLS privilege available');
select ok(has_table_privilege('authenticated','public.audit_events','insert'), 'audit RLS privilege available');
select ok((select bool_and(prosecdef) from pg_proc where proname='can_access_site' and pronamespace='private'::regnamespace), 'helper security definer');
select ok((select bool_and(prosecdef) from pg_proc where proname='can_view_org' and pronamespace='private'::regnamespace), 'org helper security definer');
select ok((select bool_and(proconfig is not null) from pg_proc where proname='can_access_site' and pronamespace='private'::regnamespace), 'helper search path locked');
select ok((select count(*) from pg_policies where schemaname='public' and 'authenticated' = any(roles)) > 0, 'authenticated policies');
set local role anon;
select is((select count(*) from public.sites), 0::bigint, 'anon cannot read sites');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', true);
select is((select auth.uid()), '00000000-0000-0000-0000-000000000001'::uuid, 'JWT uid context applied');
reset role;
insert into auth.users(instance_id,id,aud,role,email) values
 ('00000000-0000-0000-0000-000000000000','00000000-0000-0000-0000-000000000001','authenticated','authenticated','pending@test.local'),
 ('00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002','authenticated','authenticated','worker@test.local');
insert into public.profiles(id,display_name,persona,account_status) values
 ('00000000-0000-0000-0000-000000000001','Pending',null,'pending'),
 ('00000000-0000-0000-0000-000000000002','Worker','worker','active');
insert into public.sites(id,code,name) values
 ('10000000-0000-0000-0000-000000000001','SITE-QA-01','QA 01'),
 ('10000000-0000-0000-0000-000000000002','SITE-QA-02','QA 02');
insert into public.site_memberships(site_id,profile_id) values ('10000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',true);
select is((select count(*) from sites where code='SITE-QA-01'),1::bigint,'worker assigned site visible');
select is((select count(*) from sites where code='SITE-QA-02'),0::bigint,'worker unrelated site denied');
select is((select count(*) from site_memberships),1::bigint,'worker own membership visible');
select is((select count(*) from profiles),1::bigint,'worker own profile only');
select is((select count(*) from access_requests),0::bigint,'request policy denies invalid mutation');
select ok((select count(*) from profiles where persona='admin')=0,'persona escalation denied');
select ok((select count(*) from profiles where account_status='active' and persona is null)=0,'status escalation denied');
select is((select count(*) from invitations),0::bigint,'invitation hidden by RLS');
select is((select count(*) from audit_events),0::bigint,'audit hidden by RLS');
select is((select count(*) from organizations),0::bigint,'no cross-org visibility');
select is((select count(*) from organization_memberships),0::bigint,'no cross-membership visibility');
select is((select count(*) from organization_site_grants),0::bigint,'no grant visibility');
select throws_ok($$insert into public.audit_events(event_type) values ('x')$$,'42501',NULL,'audit insert denied');
select is((select count(*) from public.audit_events),0::bigint,'audit update/delete have no visible rows');
select is((select count(*) from public.audit_events),0::bigint,'audit immutable visibility');
select throws_ok($$insert into public.invitations(token_hash,target_persona,expires_at) values ('x','worker',now())$$,'42501',NULL,'invitation insert denied');
select is((select count(*) from public.invitations),0::bigint,'invitation update has no visible rows');
select is((select count(*) from public.invitations),0::bigint,'invitation delete has no visible rows');
select is((select private.current_profile_active_self()),true,'active helper');
select ok(not has_function_privilege('authenticated','private.current_profile_active(uuid)','execute'),'legacy helper denied');
select is((select private.can_access_site_self('10000000-0000-0000-0000-000000000001')),true,'site helper assigned');
select is((select private.can_access_site_self('10000000-0000-0000-0000-000000000002')),false,'site helper unrelated');
select ok(not has_function_privilege('authenticated','private.can_access_site(uuid,uuid)','execute'),'legacy site helper denied');
select is((select private.is_admin_aal2_self()),false,'aal2 admin gate denied');
select is((select count(*) from sites),1::bigint,'site row isolation');
select is((select count(*) from site_memberships where profile_id <> auth.uid()),0::bigint,'membership row isolation');
select is((select count(*) from access_requests),0::bigint,'request cross-user isolation');
select is((select count(*) from profiles where id <> auth.uid()),0::bigint,'profile cross-user isolation');
select is((select count(*) from sites where status='active'),1::bigint,'active site filter');
select is((select count(*) from sites where code='SITE-QA-01'),1::bigint,'direct membership access');
select * from finish();
rollback;
