export type Factor={id:string;status:'verified'|'unverified'};
export type PendingEnrollment={factorId:string;qr:string;secret:string;createdAt:number;friendlyName:string};
export const PENDING_MFA_KEY='inopnc.admin.mfa.pending.v1';
export const PENDING_MFA_TTL_MS=10*60*1000;
export type MfaApi={listFactors:()=>Promise<{data:{totp:Factor[]}|null;error:Error|null}>;unenroll:(arg:{factorId:string})=>Promise<{error:Error|null}>;enroll:(arg:{factorType:'totp';friendlyName:string})=>Promise<{data:{id:string;totp:{secret:string;qr_code:string}}|null;error:Error|null}>};
const storage=()=>typeof window==='undefined'?undefined:window.sessionStorage;
const readPending=()=>{try{const raw=storage()?.getItem(PENDING_MFA_KEY);if(!raw)return;const p=JSON.parse(raw) as PendingEnrollment;if(typeof p.factorId==='string'&&typeof p.qr==='string'&&typeof p.secret==='string'&&typeof p.friendlyName==='string'&&p.friendlyName&&Number.isFinite(p.createdAt))return p;}catch{};return;};
export const clearPending=()=>storage()?.removeItem(PENDING_MFA_KEY);
export async function initializeMfa(api:MfaApi,now=Date.now()){const listed=await api.listFactors();if(listed.error)throw new Error('init');const verified=listed.data?.totp.find(f=>f.status==='verified');if(verified){clearPending();return {mode:'challenge' as const,factorId:verified.id};}const pending=readPending();if(pending&&now-pending.createdAt<=PENDING_MFA_TTL_MS)return {mode:'enrollment' as const,factorId:pending.factorId,secret:pending.secret,qr:pending.qr};if(pending){const removed=await api.unenroll({factorId:pending.factorId});clearPending();if(removed.error)throw new Error('cleanup');}const friendlyName=`INOPNC Admin ${typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`${now}-${Math.random().toString(36).slice(2)}`}`;const enrolled=await api.enroll({factorType:'totp',friendlyName});if(enrolled.error||!enrolled.data)throw new Error('enroll');const result={factorId:enrolled.data.id,qr:enrolled.data.totp.qr_code,secret:enrolled.data.totp.secret,createdAt:now,friendlyName};storage()?.setItem(PENDING_MFA_KEY,JSON.stringify(result));return {mode:'enrollment' as const,...result};}
