create schema if not exists private;
create or replace function private.current_profile_active(uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path = '' as $$ select exists (select 1 from public.profiles p where p.id=uid and p.account_status='active') $$;
create or replace function private.is_admin_aal2(uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path = '' as $$ select exists (select 1 from public.profiles p where p.id=uid and p.persona='admin' and p.account_status='active') and coalesce((select auth.jwt()->>'aal'),'')='aal2' $$;
create or replace function private.can_access_site(sid uuid, uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path = '' as $$ select private.current_profile_active(uid) and exists (select 1 from public.sites s join public.site_memberships m on m.site_id=s.id where s.id=sid and s.status='active' and m.profile_id=uid and m.status='active') or private.current_profile_active(uid) and exists (select 1 from public.sites s join public.organization_site_grants g on g.site_id=s.id join public.organization_memberships m on m.organization_id=g.organization_id join public.organizations o on o.id=g.organization_id where s.id=sid and s.status='active' and g.status='active' and m.profile_id=uid and m.status='active' and o.type='partner' and o.status='active') $$;
create or replace function private.can_view_org(oid uuid, uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path = '' as $$ select private.current_profile_active(uid) and exists (select 1 from public.organization_memberships m join public.organizations o on o.id=m.organization_id where m.organization_id=oid and m.profile_id=uid and m.status='active' and o.status='active') $$;
revoke all on function private.current_profile_active(uuid), private.is_admin_aal2(uuid), private.can_access_site(uuid,uuid), private.can_view_org(uuid,uuid) from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.current_profile_active(uuid), private.is_admin_aal2(uuid), private.can_access_site(uuid,uuid), private.can_view_org(uuid,uuid) to authenticated;
alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_memberships enable row level security;
alter table public.sites enable row level security;
alter table public.site_memberships enable row level security;
alter table public.organization_site_grants enable row level security;
alter table public.invitations enable row level security;
alter table public.access_requests enable row level security;
alter table public.audit_events enable row level security;
create policy profiles_self_select on public.profiles for select to authenticated using (id=auth.uid());
create policy profiles_pending_self_insert on public.profiles for insert to authenticated with check (id=auth.uid() and persona is null and account_status='pending');
create policy organizations_visible on public.organizations for select to authenticated using (private.can_view_org(id));
create policy organizations_admin_manage on public.organizations for all to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy memberships_visible on public.organization_memberships for select to authenticated using (profile_id=auth.uid() or private.is_admin_aal2());
create policy memberships_admin_manage on public.organization_memberships for all to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy sites_visible on public.sites for select to authenticated using (private.can_access_site(id));
create policy sites_admin_manage on public.sites for all to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy site_memberships_visible on public.site_memberships for select to authenticated using (profile_id=auth.uid() or private.is_admin_aal2());
create policy site_memberships_admin_manage on public.site_memberships for all to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy grants_partner_visible on public.organization_site_grants for select to authenticated using (private.can_view_org(organization_id));
create policy grants_admin_manage on public.organization_site_grants for all to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy access_requests_self_select on public.access_requests for select to authenticated using (profile_id=auth.uid() or private.is_admin_aal2());
create policy access_requests_self_insert on public.access_requests for insert to authenticated with check (profile_id=auth.uid() and status='pending' and reviewed_by is null and reviewed_at is null and rejection_reason is null);
create policy access_requests_admin_update on public.access_requests for update to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy access_requests_admin_delete on public.access_requests for delete to authenticated using (private.is_admin_aal2());
revoke all on public.invitations, public.audit_events from anon, authenticated;
create policy invitations_admin_manage on public.invitations for all to authenticated using (private.is_admin_aal2()) with check (private.is_admin_aal2());
create policy audit_admin_select on public.audit_events for select to authenticated using (private.is_admin_aal2());
create policy audit_admin_insert on public.audit_events for insert to authenticated with check (private.is_admin_aal2());
create policy audit_immutable_update on public.audit_events for update to authenticated using (false) with check (false);
create policy audit_immutable_delete on public.audit_events for delete to authenticated using (false);
