create type public.persona as enum ('admin','site_manager','worker','production_manager','partner');
create type public.account_status as enum ('pending','active','suspended','deactivated');
create type public.site_access_level as enum ('view','collaborate');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null, persona public.persona, account_status public.account_status not null default 'pending', avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint profiles_active_persona_check check (account_status <> 'active' or persona is not null), constraint profiles_display_name_check check (length(trim(display_name)) > 0));
create table public.organizations (id uuid primary key default gen_random_uuid(), type text not null check (type in ('inopnc','partner')), name text not null, normalized_name text not null, business_number text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organization_memberships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, membership_type text not null, job_title text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, profile_id));
create table public.sites (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.site_memberships (id uuid primary key default gen_random_uuid(), site_id uuid not null references public.sites(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, access_level public.site_access_level not null default 'view', status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (site_id, profile_id));
create table public.organization_site_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, site_id uuid not null references public.sites(id) on delete cascade, access_level public.site_access_level not null default 'view', status text not null default 'active', unique (organization_id, site_id));
create table public.invitations (id uuid primary key default gen_random_uuid(), token_hash text not null unique, target_persona public.persona not null, expires_at timestamptz not null, accepted_at timestamptz, revoked_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.access_requests (id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id), name text not null, company text, job_title text, contact text, status text not null default 'pending', created_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), event_type text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index organization_memberships_profile_idx on public.organization_memberships(profile_id);
create index organization_memberships_org_idx on public.organization_memberships(organization_id);
create index site_memberships_profile_idx on public.site_memberships(profile_id);
create index site_memberships_site_idx on public.site_memberships(site_id);
create index grants_org_idx on public.organization_site_grants(organization_id);
create index grants_site_idx on public.organization_site_grants(site_id);
create index access_requests_status_idx on public.access_requests(status);
create index invitations_expires_idx on public.invitations(expires_at);
create index audit_events_actor_idx on public.audit_events(actor_id);
create index audit_events_created_idx on public.audit_events(created_at);
